"""Minimal artifacts in each format vizops reads, and the malformed variants
the tests use as negative controls.

Every `bad_*` here is an input a check is known to REJECT. A check with only
positive controls is not a check: these are what say that the refusals fire on
the thing they name, rather than that nothing has gone wrong yet.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

GRAPH: dict[str, Any] = {
    "format": "finite typed relationship graph 1",
    "generated": "Generated by proof_records/generate_ledgers.py from ledger.json; do not edit.",
    "repository": "larsbx/example",
    "source": "ledger.json",
    "edge_types": ["implicative", "part-whole"],
    "provenance_classes": ["theorem-backed", "open", "declared"],
    "nodes": [
        {"id": "Root", "kind": "claim", "label": "OPEN_FRONTIER", "provenance": "open", "statement": "the root holds"},
        {"id": "Block", "kind": "claim", "label": "SCAFFOLDED", "provenance": "open", "statement": "a block holds"},
        {"id": "Proved", "kind": "claim", "label": "PROVED", "provenance": "theorem-backed", "statement": "proved"},
        {"id": "Assumed", "kind": "assumption set", "label": "assumption set", "provenance": "declared", "members": ["Block"]},
    ],
    "edges": [
        {"type": "implicative", "source": "Block", "target": "Root"},
        {"type": "part-whole", "source": "Block", "target": "Assumed"},
    ],
}

CATALOGUE = """\
schema_version = 1
title = "Example catalogue"

[[taxonomy]]
id = "dynamics"
name = "Substitution dynamics"
description = "Words and their finite symbolic dynamics."

[[taxonomy]]
id = "algebra"
name = "Exact algebra"

[[object]]
id = "substitution"
name = "Substitution"
taxonomy = "dynamics"
status = "definition"
scope = "A non-erasing morphism."
related = ["incidence-matrix"]

[[object]]
id = "incidence-matrix"
name = "Incidence matrix"
taxonomy = "algebra"
status = "definition"

[[object]]
id = "wedge-defect"
name = "Wedge defect"
taxonomy = "algebra"
status = "open-boundary"
related = ["substitution"]
"""


WAKE_MODULE = """\
from fractions import Fraction


def double(theta):
    return 2 * theta % 1


def mechanical(p, q, r):
    return int("".join("1" if (r + k * p) % q >= q - p else "0" for k in range(q)), 2)


def rotation_cycle(p, q):
    x, out = Fraction(mechanical(p, q, 0), 2 ** q - 1), []
    for _ in range(q):
        out.append(x)
        x = double(x)
    return tuple(sorted(out))


def wake(p, q):
    c = rotation_cycle(p, q)
    return min(zip(c, c[1:]), key=lambda pair: pair[1] - pair[0])
"""


def graph(**overrides: Any) -> bytes:
    return json.dumps({**GRAPH, **overrides}).encode("utf-8")


def mutate(path: str, value: Any) -> bytes:
    """A graph with one field of one node or edge replaced, e.g. `nodes.0.provenance`."""
    data = json.loads(json.dumps(GRAPH))
    where, *rest = path.split(".")
    target = data[where]
    for key in rest[:-1]:
        target = target[int(key)] if isinstance(target, list) else target[key]
    target[rest[-1] if not rest[-1].isdigit() else int(rest[-1])] = value
    return json.dumps(data).encode("utf-8")


def estate(root: Path, *, graph_bytes: bytes | None = None, catalogue: str | None = None) -> Path:
    """A checkout tree the manifest's two scenes resolve against."""
    from vizops.sources import load

    for scene in load():
        if scene.vendored:
            continue  # read from vendor/, pinned in vendored.toml; never a fixture's to write
        artifact = scene.artifact(root)
        artifact.parent.mkdir(parents=True, exist_ok=True)
        if scene.adapter == "typed_graph":
            payload = graph_bytes or graph()
        elif scene.adapter == "object_catalogue":
            payload = (catalogue or CATALOGUE).encode("utf-8")
        elif scene.adapter == "wake_module":
            payload = WAKE_MODULE.encode("utf-8")
        else:
            raise AssertionError(f"test fixture has no source for adapter {scene.adapter!r}")
        artifact.write_bytes(payload)
    return root


VENDOR_ROOT = Path(__file__).resolve().parents[1]


def drifted_vendor(tmp_path: Path, monkeypatch, change: bytes = b"\n# a local patch\n") -> Path:
    """A copy of vendor/ and vendored.toml under `tmp_path`, made the one vizops
    reads, with `change` appended to the copy of rational_dynamics_py/doubling.py.

    Tests break the copy, never the repository's own vendored files: a vendored
    scene's `artifact()` is the real file under vendor/.
    """
    from vizops import sources

    shutil.copy(VENDOR_ROOT / "vendored.toml", tmp_path / "vendored.toml")
    shutil.copytree(VENDOR_ROOT / "vendor", tmp_path / "vendor", ignore=shutil.ignore_patterns("__pycache__"))
    doubling = tmp_path / "vendor" / "python" / "rational_dynamics_py" / "doubling.py"
    doubling.write_bytes(doubling.read_bytes() + change)
    monkeypatch.setattr(sources, "VENDORED", tmp_path / "vendored.toml")
    return doubling
