"""Minimal artifacts in each format vizops reads, and the malformed variants
the tests use as negative controls.

Every `bad_*` here is an input a check is known to REJECT. A check with only
positive controls is not a check: these are what say that the refusals fire on
the thing they name, rather than that nothing has gone wrong yet.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

GRAPH: dict[str, Any] = {
    "format": "finite typed relationship graph 1",
    "generated": "Generated by proof_records/generate_ledgers.py from ledger.json; do not edit.",
    "repository": "larsbx/example",
    "source": "ledger.json",
    "edge_types": ["implicative", "part-whole"],
    "provenance_classes": ["theorem-backed", "open", "declared"],
    "nodes": [
        {"id": "Root", "kind": "claim", "label": "OPEN_FRONTIER", "provenance": "open", "statement": "the root holds"},
        {"id": "Block", "kind": "claim", "label": "SCAFFOLDED", "provenance": "open", "statement": "a block holds"},
        {"id": "Proved", "kind": "claim", "label": "PROVED", "provenance": "theorem-backed", "statement": "proved"},
        {"id": "Assumed", "kind": "assumption set", "label": "assumption set", "provenance": "declared", "members": ["Block"]},
    ],
    "edges": [
        {"type": "implicative", "source": "Block", "target": "Root"},
        {"type": "part-whole", "source": "Block", "target": "Assumed"},
    ],
}

CATALOGUE = """\
schema_version = 1
title = "Example catalogue"

[[taxonomy]]
id = "dynamics"
name = "Substitution dynamics"
description = "Words and their finite symbolic dynamics."

[[taxonomy]]
id = "algebra"
name = "Exact algebra"

[[object]]
id = "substitution"
name = "Substitution"
taxonomy = "dynamics"
status = "definition"
scope = "A non-erasing morphism."
related = ["incidence-matrix"]

[[object]]
id = "incidence-matrix"
name = "Incidence matrix"
taxonomy = "algebra"
status = "definition"

[[object]]
id = "wedge-defect"
name = "Wedge defect"
taxonomy = "algebra"
status = "open-boundary"
related = ["substitution"]
"""


def graph(**overrides: Any) -> bytes:
    return json.dumps({**GRAPH, **overrides}).encode("utf-8")


def mutate(path: str, value: Any) -> bytes:
    """A graph with one field of one node or edge replaced, e.g. `nodes.0.provenance`."""
    data = json.loads(json.dumps(GRAPH))
    where, *rest = path.split(".")
    target = data[where]
    for key in rest[:-1]:
        target = target[int(key)] if isinstance(target, list) else target[key]
    target[rest[-1] if not rest[-1].isdigit() else int(rest[-1])] = value
    return json.dumps(data).encode("utf-8")


def estate(root: Path, *, graph_bytes: bytes | None = None, catalogue: str | None = None) -> Path:
    """A checkout tree the manifest's two scenes resolve against."""
    from vizops.sources import load

    for scene in load():
        artifact = scene.artifact(root)
        artifact.parent.mkdir(parents=True, exist_ok=True)
        artifact.write_bytes(
            (graph_bytes or graph()) if scene.adapter == "typed_graph" else (catalogue or CATALOGUE).encode("utf-8")
        )
    return root
